In [2]:
import pandas as pd
import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv("/content/drive/MyDrive/heart_disease_risk_2026.csv")
df.head()

,patient_id,age,sex,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,...,family_history,smoker_status,alcohol_units_per_week,exercise_minutes_per_week,sleep_hours,stress_score,wearable_owner,daily_steps,diet_quality_score,has_heart_disease
0,1,44,Male,117,74,193,57,106,119,112,...,False,Never,2.9,86,5.4,19.8,True,7731,62.9,0
1,2,57,Male,139,94,185,69,110,35,114,...,False,Never,3.0,132,4.3,45.8,True,2629,74.6,1
2,3,29,Male,128,78,197,52,108,157,95,...,False,Current,3.5,128,5.1,17.7,True,9290,65.7,0
3,4,72,Male,132,86,197,59,104,143,92,...,False,Never,2.7,18,6.8,63.6,True,7373,48.5,1
4,5,62,Female,116,75,154,65,75,104,135,...,True,Former,3.3,24,8.2,58.7,False,6331,47.3,1

In [4]:
df=df.drop(columns=['patient_id'])
df['has_heart_disease']=df['has_heart_disease']

In [5]:
x=df.drop(columns=['has_heart_disease'])
y=df['has_heart_disease']

In [6]:
x_encoded = pd.get_dummies(x,drop_first=True)
x_encoded

,age,resting_bp_systolic,resting_bp_diastolic,cholesterol_total,hdl,ldl,triglycerides,fasting_blood_sugar,hba1c,bmi,...,stress_score,wearable_owner,daily_steps,diet_quality_score,sex_Male,chest_pain_type_Atypical Angina,chest_pain_type_Non-Anginal Pain,chest_pain_type_Typical Angina,smoker_status_Former,smoker_status_Never
0,44,117,74,193,57,106,119,112,5.2,26.5,...,19.8,True,7731,62.9,True,False,False,False,False,True
1,57,139,94,185,69,110,35,114,5.9,20.8,...,45.8,True,2629,74.6,True,False,True,False,False,True
2,29,128,78,197,52,108,157,95,5.5,24.5,...,17.7,True,9290,65.7,True,False,False,False,False,False
3,72,132,86,197,59,104,143,92,4.8,27.3,...,63.6,True,7373,48.5,True,False,False,False,False,True
4,62,116,75,154,65,75,104,135,6.2,26.0,...,58.7,False,6331,47.3,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,36,108,63,178,68,82,158,96,5.3,25.1,...,51.1,False,7144,58.1,False,False,False,True,False,True
8996,44,112,73,213,54,139,102,125,5.9,23.6,...,37.1,False,7395,68.9,False,False,False,False,True,False
8997,57,144,93,198,66,113,79,102,5.7,28.2,...,46.3,False,7424,70.2,False,False,False,False,False,True
8998,61,130,70,220,68,135,109,104,5.5,27.5,...,66.5,False,5716,43.8,False,False,False,False,True,False
8999,63,152,104,215,64,117,109,120,5.0,22.1,...,54.1,False,3860,54.5,False,False,False,False,False,True

In [7]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_encoded)
x_scaled

array([[-0.76705476, -0.78813079, -0.62058413, ..., -0.35712317,
        -0.61124985,  0.89845919],
       [ 0.23238182,  0.80995516,  1.20768055, ..., -0.35712317,
        -0.61124985,  0.89845919],
       [-1.92025081,  0.01091218, -0.2549312 , ..., -0.35712317,
        -0.61124985, -1.11301661],
       ...,
       [ 0.23238182,  1.17315651,  1.11626732, ..., -0.35712317,
        -0.61124985,  0.89845919],
       [ 0.53990077,  0.15619272, -0.98623707, ..., -0.35712317,
         1.63599223, -1.11301661],
       [ 0.69366024,  1.75427868,  2.1218129 , ..., -0.35712317,
        -0.61124985,  0.89845919]])

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)
print(x_train.shape)

(7200, 28)

In [9]:
from keras.models import Sequential
from keras.layers import Dense, Input

In [10]:
model = Sequential()
model.add(Input(shape=(x_train.shape[1],)))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [11]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=100, verbose=2)

Epoch 1/100
225/225 - 2s - 7ms/step - accuracy: 0.7872 - loss: 0.4459
Epoch 2/100
225/225 - 0s - 2ms/step - accuracy: 0.8756 - loss: 0.3005
Epoch 3/100
225/225 - 0s - 2ms/step - accuracy: 0.8868 - loss: 0.2724
Epoch 4/100
225/225 - 0s - 2ms/step - accuracy: 0.8926 - loss: 0.2606
Epoch 5/100
225/225 - 0s - 2ms/step - accuracy: 0.8954 - loss: 0.2533
Epoch 6/100
225/225 - 0s - 2ms/step - accuracy: 0.8976 - loss: 0.2487
Epoch 7/100
225/225 - 0s - 2ms/step - accuracy: 0.9003 - loss: 0.2446
Epoch 8/100
225/225 - 0s - 2ms/step - accuracy: 0.9015 - loss: 0.2416
Epoch 9/100
225/225 - 0s - 2ms/step - accuracy: 0.9021 - loss: 0.2396
Epoch 10/100
225/225 - 0s - 2ms/step - accuracy: 0.9029 - loss: 0.2375
Epoch 11/100
225/225 - 0s - 2ms/step - accuracy: 0.9029 - loss: 0.2368
Epoch 12/100
225/225 - 0s - 2ms/step - accuracy: 0.9040 - loss: 0.2350
Epoch 13/100
225/225 - 1s - 3ms/step - accuracy: 0.9033 - loss: 0.2341
Epoch 14/100
225/225 - 0s - 2ms/step - accuracy: 0.9053 - loss: 0.2332
Epoch 15/100
225/225 - 1s - 2ms/step - accuracy: 0.9061 - loss: 0.2319
Epoch 16/100
225/225 - 1s - 3ms/step - accuracy: 0.9044 - loss: 0.2306
Epoch 17/100
225/225 - 1s - 3ms/step - accuracy: 0.9038 - loss: 0.2303
Epoch 18/100
225/225 - 1s - 3ms/step - accuracy: 0.9062 - loss: 0.2294
Epoch 19/100
225/225 - 1s - 6ms/step - accuracy: 0.9079 - loss: 0.2278
Epoch 20/100
225/225 - 1s - 3ms/step - accuracy: 0.9071 - loss: 0.2276
Epoch 21/100
225/225 - 1s - 4ms/step - accuracy: 0.9064 - loss: 0.2265
Epoch 22/100
225/225 - 1s - 2ms/step - accuracy: 0.9083 - loss: 0.2259
Epoch 23/100
225/225 - 0s - 2ms/step - accuracy: 0.9071 - loss: 0.2252
Epoch 24/100
225/225 - 1s - 3ms/step - accuracy: 0.9076 - loss: 0.2248
Epoch 25/100
225/225 - 0s - 2ms/step - accuracy: 0.9081 - loss: 0.2241
Epoch 26/100
225/225 - 0s - 2ms/step - accuracy: 0.9094 - loss: 0.2230
Epoch 27/100
225/225 - 0s - 2ms/step - accuracy: 0.9083 - loss: 0.2228
Epoch 28/100
225/225 - 0s - 2ms/step - accuracy: 0.9093 - loss: 0.2214
Epoch 29/100
225/225 - 0s - 2ms/step - accuracy: 0.9101 - loss: 0.2209
Epoch 30/100
225/225 - 0s - 2ms/step - accuracy: 0.9103 - loss: 0.2212
Epoch 31/100
225/225 - 0s - 2ms/step - accuracy: 0.9107 - loss: 0.2198
Epoch 32/100
225/225 - 0s - 2ms/step - accuracy: 0.9104 - loss: 0.2193
Epoch 33/100
225/225 - 0s - 2ms/step - accuracy: 0.9115 - loss: 0.2188
Epoch 34/100
225/225 - 0s - 2ms/step - accuracy: 0.9106 - loss: 0.2180
Epoch 35/100
225/225 - 1s - 3ms/step - accuracy: 0.9101 - loss: 0.2176
Epoch 36/100
225/225 - 0s - 2ms/step - accuracy: 0.9115 - loss: 0.2172
Epoch 37/100
225/225 - 0s - 2ms/step - accuracy: 0.9125 - loss: 0.2168
Epoch 38/100
225/225 - 0s - 2ms/step - accuracy: 0.9118 - loss: 0.2159
Epoch 39/100
225/225 - 0s - 2ms/step - accuracy: 0.9128 - loss: 0.2157
Epoch 40/100
225/225 - 0s - 2ms/step - accuracy: 0.9126 - loss: 0.2151
Epoch 41/100
225/225 - 0s - 2ms/step - accuracy: 0.9115 - loss: 0.2153
Epoch 42/100
225/225 - 1s - 3ms/step - accuracy: 0.9115 - loss: 0.2147
Epoch 43/100
225/225 - 1s - 3ms/step - accuracy: 0.9129 - loss: 0.2135
Epoch 44/100
225/225 - 1s - 3ms/step - accuracy: 0.9111 - loss: 0.2133
Epoch 45/100
225/225 - 1s - 3ms/step - accuracy: 0.9129 - loss: 0.2127
Epoch 46/100
225/225 - 1s - 6ms/step - accuracy: 0.9133 - loss: 0.2129
Epoch 47/100
225/225 - 1s - 3ms/step - accuracy: 0.9124 - loss: 0.2128
Epoch 48/100
225/225 - 0s - 2ms/step - accuracy: 0.9128 - loss: 0.2123
Epoch 49/100
225/225 - 0s - 2ms/step - accuracy: 0.9135 - loss: 0.2121
Epoch 50/100
225/225 - 0s - 2ms/step - accuracy: 0.9137 - loss: 0.2109
Epoch 51/100
225/225 - 0s - 2ms/step - accuracy: 0.9132 - loss: 0.2107
Epoch 52/100
225/225 - 0s - 2ms/step - accuracy: 0.9126 - loss: 0.2103
Epoch 53/100
225/225 - 1s - 3ms/step - accuracy: 0.9124 - loss: 0.2106
Epoch 54/100
225/225 - 0s - 2ms/step - accuracy: 0.9122 - loss: 0.2104
Epoch 55/100
225/225 - 0s - 2ms/step - accuracy: 0.9137 - loss: 0.2097
Epoch 56/100
225/225 - 0s - 2ms/step - accuracy: 0.9143 - loss: 0.2091
Epoch 57/100
225/225 - 0s - 2ms/step - accuracy: 0.9136 - loss: 0.2080
Epoch 58/100
225/225 - 0s - 2ms/step - accuracy: 0.9143 - loss: 0.2085
Epoch 59/100
225/225 - 0s - 2ms/step - accuracy: 0.9139 - loss: 0.2084
Epoch 60/100
225/225 - 0s - 2ms/step - accuracy: 0.9131 - loss: 0.2079
Epoch 61/100
225/225 - 1s - 3ms/step - accuracy: 0.9125 - loss: 0.2071
Epoch 62/100
225/225 - 0s - 2ms/step - accuracy: 0.9149 - loss: 0.2075
Epoch 63/100
225/225 - 0s - 2ms/step - accuracy: 0.9132 - loss: 0.2069
Epoch 64/100
225/225 - 0s - 2ms/step - accuracy: 0.9156 - loss: 0.2064
Epoch 65/100
225/225 - 0s - 2ms/step - accuracy: 0.9172 - loss: 0.2058
Epoch 66/100
225/225 - 0s - 2ms/step - accuracy: 0.9143 - loss: 0.2059
Epoch 67/100
225/225 - 1s - 3ms/step - accuracy: 0.9160 - loss: 0.2052
Epoch 68/100
225/225 - 0s - 2ms/step - accuracy: 0.9136 - loss: 0.2056
Epoch 69/100
225/225 - 0s - 2ms/step - accuracy: 0.9174 - loss: 0.2052
Epoch 70/100
225/225 - 1s - 2ms/step - accuracy: 0.9167 - loss: 0.2046
Epoch 71/100
225/225 - 1s - 3ms/step - accuracy: 0.9158 - loss: 0.2045
Epoch 72/100
225/225 - 1s - 3ms/step - accuracy: 0.9153 - loss: 0.2040
Epoch 73/100
225/225 - 1s - 3ms/step - accuracy: 0.9167 - loss: 0.2030
Epoch 74/100
225/225 - 1s - 3ms/step - accuracy: 0.9176 - loss: 0.2031
Epoch 75/100
225/225 - 1s - 6ms/step - accuracy: 0.9176 - loss: 0.2025
Epoch 76/100
225/225 - 1s - 2ms/step - accuracy: 0.9167 - loss: 0.2027
Epoch 77/100
225/225 - 0s - 2ms/step - accuracy: 0.9168 - loss: 0.2025
Epoch 78/100
225/225 - 0s - 2ms/step - accuracy: 0.9174 - loss: 0.2021
Epoch 79/100
225/225 - 0s - 2ms/step - accuracy: 0.9169 - loss: 0.2010
Epoch 80/100
225/225 - 0s - 2ms/step - accuracy: 0.9171 - loss: 0.2008
Epoch 81/100
225/225 - 0s - 2ms/step - accuracy: 0.9181 - loss: 0.2005
Epoch 82/100
225/225 - 0s - 2ms/step - accuracy: 0.9182 - loss: 0.2010
Epoch 83/100
225/225 - 0s - 2ms/step - accuracy: 0.9186 - loss: 0.2001
Epoch 84/100
225/225 - 0s - 2ms/step - accuracy: 0.9175 - loss: 0.1993
Epoch 85/100
225/225 - 0s - 2ms/step - accuracy: 0.9174 - loss: 0.1993
Epoch 86/100
225/225 - 0s - 2ms/step - accuracy: 0.9178 - loss: 0.1988
Epoch 87/100
225/225 - 0s - 2ms/step - accuracy: 0.9197 - loss: 0.1988
Epoch 88/100
225/225 - 0s - 2ms/step - accuracy: 0.9196 - loss: 0.1987
Epoch 89/100
225/225 - 0s - 2ms/step - accuracy: 0.9203 - loss: 0.1982
Epoch 90/100
225/225 - 0s - 2ms/step - accuracy: 0.9194 - loss: 0.1985
Epoch 91/100
225/225 - 0s - 2ms/step - accuracy: 0.9190 - loss: 0.1982
Epoch 92/100
225/225 - 0s - 2ms/step - accuracy: 0.9206 - loss: 0.1984
Epoch 93/100
225/225 - 0s - 2ms/step - accuracy: 0.9208 - loss: 0.1974
Epoch 94/100
225/225 - 0s - 2ms/step - accuracy: 0.9204 - loss: 0.1973
Epoch 95/100
225/225 - 0s - 2ms/step - accuracy: 0.9196 - loss: 0.1974
Epoch 96/100
225/225 - 0s - 2ms/step - accuracy: 0.9203 - loss: 0.1964
Epoch 97/100
225/225 - 0s - 2ms/step - accuracy: 0.9186 - loss: 0.1969
Epoch 98/100
225/225 - 0s - 2ms/step - accuracy: 0.9201 - loss: 0.1968
Epoch 99/100
225/225 - 0s - 2ms/step - accuracy: 0.9207 - loss: 0.1968
Epoch 100/100
225/225 - 1s - 3ms/step - accuracy: 0.9212 - loss: 0.1962

In [13]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'\nTest Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')

57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8894 - loss: 0.2845

Test Loss: 0.2845, Test Accuracy: 0.8894

In [14]:
prediction = model.predict(x_test)
print(prediction)

57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[3.6486378e-01]
 [4.1729701e-01]
 [1.9247549e-03]
 ...
 [6.1550429e-03]
 [8.6501117e-05]
 [1.0106517e-03]]